### ISSUE TITLE
Generate the synthetic reflection image

### ISSUE THREAD

**Issue by csqiangwen** [NVlabs/ReflectNet#1]
Thanks for your nice work.
Could you tell me how to generate the synthetic reflection image with two .png files by your method?

**Comment by PatWie** [comment]
The data reader uses an LMDB storage. However, you can inject your own png directly by rewriting

https://github.com/NVlabs/ReflectNet/blob/fcd028f047bf9063ac22b78788e1f58a3021f825/ReflectNet/data_sampler.py#L199-L203

**Comment by zhilaAI** [comment]
Hello thank you for your nice work. I try to run the code but i do not know how . i have one error  I0 = cv2.imread(ppms[0]).astype(np.float32) / 255.
IndexError: list index out of range 
can you give me the instruction for executing code? I appreciate you
