### ISSUE TITLE
Polarized Image Collection. 

### ISSUE THREAD

**Issue by CVDOU** [NVlabs/ReflectNet#3]
Thanks for your awesome work.
I am interested in your dataset (URD). In your paper, you mentioned that you collect three polarization images (&pi;/4 , &pi;/2, &pi; *3/4) for each example. I wonder to know if the polarization angles should be exact &pi;/4 , &pi;/2, &pi; *3/4. Or the angles are randomly set?

**Comment by PatWie** [comment]
As written in the paper the starting angle is arbitrary. Only the offsets are fixed. The order although is like you wrote.

**Comment by CVDOU** [comment]
> As written in the paper the starting angle is arbitrary. Only the offsets are fixed. The order although is like you wrote.

Thanks. 
Do you use a circular polarization filter to collect polarized images? The circular polarization filter does not appear to provide offset. If we set the offset manually every time, it can be difficult and inaccurate. Maybe I misunderstood some steps, can you provide more details on how to adjust the offset?

**Comment by PatWie** [comment]
No, we used a  linear polarization filter. Adjusting the offset has been done manually. I added a marker on the filter itself. And I changed the rotation by hand -- with all the disadvantages (eg. moving the camera a bit). But this is reflected in the training process.

**Comment by CVDOU** [comment]
> No, we used a linear polarization filter. Adjusting the offset has been done manually. I added a marker on the filter itself. And I changed the rotation by hand -- with all the disadvantages (eg. moving the camera a bit). But this is reflected in the training process.

Thanks a lot.
