### ISSUE TITLE
Error occurs in the Kong_et_al method

### ISSUE THREAD

**Issue by CVDOU** [NVlabs/ReflectNet#4]
verify.cu:11:25: fatal error: gtest/gtest.h: No such file or directory
 #include "gtest/gtest.h"

**Comment by PatWie** [comment]
You will need to install gtest before:
```bash
sudo apt-get install libgtest-dev
```

**Comment by CVDOU** [comment]
> You will need to install gtest before:
> 
> ```shell
> sudo apt-get install libgtest-dev
> ```

Thanks. 
The outputs are "IT_versions.fbin" and "IR_versions.fbin". Are they the transmitted image and reflected image respectively? How to save them into 'png' image?

**Comment by CVDOU** [comment]
Hi Patrick, 
I have one more question. Sorry to bother you again, but I really want to figure your code out. 
I use the code to separate your provided polarized images into reflected image and transmitted image. To achieve it, I comment the Line 92 - Line 98 in "physicalreflectionseparation.cu" and directly read three polarized images as I1, I2, I3. But  when calculating the mutual information it will need the LR and LB (Line 236), which seems directly to be got from the GT. 
Do I have some misunderstanding about the codes? If not so, how to calculate the mutual information for the real polarized images?
