### ISSUE TITLE
LMDBDataPoint

### ISSUE THREAD

**Issue by Carlyx** [NVlabs/ReflectNet#6]
Hi, your work is amazing.  I'm interested in the part that synthesizes polarized images.
When I run  `python  data_sampler.py`  in terminal（Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-74-generic x86_64)）， something bad happened.
![微信截图_20200309221429](https://user-images.githubusercontent.com/34021717/76221123-887e2f00-6253-11ea-9a55-aebbb35ebf80.png)

I did run `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`. 
So could you give me some advice on this problem, is it my mistake or is there some other problem？
Looking forward to your reply

**Comment by Carlyx** [comment]
In your NVlabs/ReflectNet/data_sampler.py,  there is `from simulator import ParabolaSample` , but only   `class ParabolaSampler` in simulator.py .   So is there a bug here , or something I misunderstanding?
@PatWie

**Comment by PatWie** [comment]
Yes, this is a typo during renaming things.. It should be `ParabolaSampler`.
Wrt to `LMDBDataPoint`:
Tensorpack has been updated within the last two years. You might want to pull an older copy of tensorpack. Ideally version `0.8.8`, see
https://github.com/NVlabs/ReflectNet/blob/master/requirements.txt

**Comment by Carlyx** [comment]
Thx, I'll give it a try.
