### ISSUE TITLE
Other files

### ISSUE THREAD

**Issue by halfendt** [NVlabs/ReflectNet#8]
Hi, do you have the files: DSC01908.ppm, DSC01909.ppm, and DSC01910.ppm?

**Comment by orazio-gallo-nvidia** [comment]
Hi halfendt,
The images from the paper are in the zip file linked on the repo main page. You'll notice that they are the raw images and they need to be converted with dcraw. We used:
`dcraw -v -W -g 1 1 -6 <raw_image_name>`
You can then directly run the eval.py script.
